apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store 
    kind: SecretStore
  target:
    name: n8n-secrets
    creationPolicy: Owner
  data:
  - secretKey: DB_POSTGRESDB_PASSWORD 
    remoteRef:
      key: DB_POSTGRESDB_PASSWORD
  - secretKey: N8N_BASIC_AUTH_PASSWORD 
    remoteRef:
      key: N8N_BASIC_AUTH_PASSWORD
  - secretKey: N8N_ENCRYPTION_KEY 
    remoteRef:
      key: N8N_ENCRYPTION_KEY
