apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: n8n
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store 
    kind: SecretStore
  target:
    name: postgres-secrets
    creationPolicy: Owner
  data:
  - secretKey: PGDATA 
    remoteRef:
      key: postgres-secrets
      property: PGDATA
  - secretKey: POSTGRES_USER 
    remoteRef:
      key: postgres-secrets
      property: POSTGRES_USER
  - secretKey: POSTGRES_DB 
    remoteRef:
      key: postgres-secrets
      property: POSTGRES_DB
  - secretKey: POSTGRES_PASSWORD 
    remoteRef:
      key: postgres-secrets
      property: POSTGRES_PASSWORD
