apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: n8n
spec:
  provider:
    aws:  
      service: SecretsManager 
      region: us-east-1   
      auth:
        secretRef:
          accessKeyIDSecretRef: 
            name: aws-secret 
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-secret
            key: access-key-secret
